### ISSUE TITLE
В meta.xml в dc:date писать дату и время сборки шаблона

### ISSUE THREAD

**Issue by sergey-s-betke** [test-st-petersburg/DocTemplates#47]
## Требуемая возможность

В meta.xml в dc:date писать дату и время сборки шаблона:

	<office:document-meta xmlns:meta="urn:oasis:names:tc:opendocument:xmlns:meta:1.0">
		<office:meta>
			<dc:date>2020-05-19T20:43:20.371000000</dc:date>
			<meta:editing-cycles>501</meta:editing-cycles>
			<meta:document-statistic meta:table-count="5" meta:image-count="1" meta:object-count="0" meta:page-count="1" meta:paragraph-count="47" meta:word-count="186" meta:character-count="1340" meta:non-whitespace-character-count="1173"/>
		</office:meta>
	</office:document-meta>

Итого:

- [x] обновлять `dc:date`
- [x] инкрементировать `meta:editing-cycles`
- [ ] обновлять `meta:document-statistic`

## Текущее поведение

Сейчас дата остаётся без изменений. Что нехорошо. Если время изменения шаблона определяется по метаданным.

**Comment by sergey-s-betke** [comment]
Обновление статистики стоит отложить, всё не столь очевидно. Необходимо выяснять, как считаются объекты в колонтитулах при повторении их на нескольких страницах, а также объекты в мастер-страницах, если они (мастер-страницы) не были использованы.

А так - аккумуляторы вполне подойдут для решения этой задачи. На первый взгляд...
