### ISSUE TITLE
Не хранить в репозитории в meta.xml вычисляемые метаданные

### ISSUE THREAD

**Issue by sergey-s-betke** [test-st-petersburg/DocTemplates#64]
## Требуемая возможность

Обновлять meta.xml в репозитории после #47

## Текущее поведение

Сейчас данные обновляются только в собираемом файле. Что не очень хорошо.

**Comment by sergey-s-betke** [comment]
По сути, перед сборкой необходимо добавить дополнительные шаги XSL трансформации исходных файлов.

После чего убрать изменения #47 непосредственно в процессе сборки.

**Comment by sergey-s-betke** [comment]
Целесообразно решать данную задачу совместно с #74

**Comment by sergey-s-betke** [comment]
Считаю целесообразным вообще убрать лишние сведения из `meta.xml`, которые могут и должны быть получены в процессе сборки. 

По этой причине предлагаю:
- [ ] убрать вообще (при оптимизации) `meta:editing-cycles`
- [ ] аналогично при оптимизации убирать `dc:date`
- [ ] и устанавливать при сборке только `dc:date` по аналогии с версией, возможно - в том же правиле
